### ISSUE TITLE
CURLPROTO_HTTP PHP error

### ISSUE THREAD

**Issue by RO55INGER** [lairdshaw/fups#9]
Hello!

I am getting the following error when running fups:

PHP Fatal error:  Uncaught Error: Undefined constant "CURLPROTO_HTTP" in /home/owner/scripts/fups/classes/CFUPSBase.php:1418
Stack trace:
#0 /home/owner/scripts/fups/fups.php(157): FUPSBase->run()
#1 {main}
  thrown in /home/owner/scripts/fups/classes/CFUPSBase.php on line 1418

Any ideas on how to fix this?

Thanks a lot!
R.

**Comment by lairdshaw** [comment]
Probably, the [Client URL Library](https://www.php.net/manual/en/book.curl.php), a PHP module required for FUPS to function correctly, is not installed, and you need to install it (via the instructions at that link).

**Comment by RO55INGER** [comment]
Thanks. I forgot to install the php-curl package. It is working now.
